server:
  port: 8084
eureka:
 client:
   service-url:
     defaultZone: http://localhost:8761/eureka/
spring:
  application:
      name: Swiggy_Food
  data:
    mongodb:
      uri: mongodb+srv://swiggy:klaus683@swiggy.li8lf.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
data:
  exception:
    cartExists: Cart id Already Exists!
    idNotFound: Cart id not found.
    noRecords: No Cart Records Found.
