server:
  port: 8085
eureka:
 client:
   service-url:
     defaultZone: http://localhost:8761/eureka/
spring:
  application:
      name: Swiggy_Payment
  data:
    mongodb:
      uri: mongodb+srv://swiggy:klaus683@swiggy.li8lf.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

