server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
    application:
      name: SwiggyApi_Gateway
    data:
      mongodb:
        uri: mongodb+srv://swiggy:klaus683@swiggy.li8lf.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
    main:
     allow-circular-references: true
     allow-bean-definition-overriding: true
    mvc:
      pathmatch:
        matching-strategy: ant-path-matcher
    cloud:
     gateway:
      routes:
      - id: cartModule
        uri: http://localhost:8084/
        predicates:
        - Path=/api/v1/cart/**
      - id: foodModule
        uri: http://localhost:8081/
        predicates:
        - Path=/api/v1/**
      - id: paymentIntegrationModule
        uri: http://localhost:8085/
        predicates:
        - Path=/api/v1/payment/**
      - id: registrationLoginModule
        uri: http://localhost:8080/
        predicates:
        - Path=/api/v1/**
      - id: restaurantModule
        uri: http://localhost:8082/
        predicates:
        - Path=/api/v1/**
          
