server: 
   port: 8080
eureka:
 client:
   service-url:
     defaultZone: http://localhost:8761/eureka/
spring:
  application:
      name: Swiggy_Registration_Login
  data:
    mongodb:
      uri: mongodb+srv://swiggy:klaus683@swiggy.li8lf.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
data:
  exception:
    msg: User Already Exists.
    pwdValidationMsg: Length of the password is too short, minimum length should be 8 character.