server:
  port: 8081
eureka:
 client:
   service-url:
     defaultZone: http://localhost:8761/eureka/
spring:
  application:
      name: Swiggy_Food
  data:
    mongodb:
      uri: mongodb+srv://swiggy:klaus683@swiggy.li8lf.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
data:
  exception:
    foodExists: Food Already Exists!
    idNotFound: Food id not found.
    noRecords: No Food Records Found.